version: '3.8'

services:
  web:
    build: .
    container_name: python-web-app
    ports:
      - "8087:8080"
    volumes:
      - .:/src
    environment: 
      - FLASK_RUN_HOST=0.0.0.0
      - MY_VAR=my_value
    command: ["bash", "-c", "wait-for-it db:3306 --timeout=60 -- bash -c 'for file in /src/*.py; do python $file; done && tail -f /dev/null'"]
    depends_on:
      - db

  db:
    image: mysql:8.0  
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root  
      MYSQL_DB: mydb  
      MYSQL_USER: user 
      MYSQL_PASSWORD: password  
    ports:
      - "3307:3306"  
    volumes:
      - db_data:/var/lib/mysql 

volumes:
  db_data:
